package Metodos.Entrada;

public class ListarEntrada {
    /*Listar entrada
SELECT ID_ENTRADA, NOMBRE, FECHA, LUGAR, PRECIOENTRADA, COMPRADOR, CANTIDAD, FECHACOMPRA
FROM ENTRADA JOIN CONCIERTO USING (ID_CONCIERTO)
    JOIN ARTISTA USING (ID_ARTISTA);*/
}
